### ISSUE TITLE
More apis to call. 

### ISSUE THREAD

**Issue by reliefs** [sleeyax/FiverrAPI#4]
This is the api's i have found available for fiverr. 
portfolioData
SharingLink
OutOfOffice
Seller-card
GigsGallery
Reviews
Footer
Sidebar

Let's find some more so we can integrate to into the FiverrAPI, also gigs api'en only call until gigList 4. #

**Comment by sleeyax** [comment]
> portfolioData
> SharingLink
> OutOfOffice
> Seller-card
> GigsGallery
> Reviews
> Footer
> Sidebar

I'm not sure what these mean, please be a little more specific, point to a complete URL part or attach some code. 

FiverrAPI is indeed far from complete and requires expansion. If you want to add additional API sections, add your methods to [fiverrapi.py](https://github.com/sleeyax/FiverrAPI/blob/master/fiverrapi/fiverrapi.py) and create a pull request. 

Also note that `get_homepage_gigs()` can't be used for retrieving 'all gigs'. I'm going to implement a method to search gigs soon.

**Comment by reliefs** [comment]
Right now i'm playing with /categories/category_id which scrapes all gigs from category. 

I think i will end up building something which scrapes all the urls from all categories and then scrapes all the urls.

**Comment by reliefs** [comment]
Right now i'm playing with /categories/category_id which scrapes all gigs from category.

I think i will end up building something which scrapes all the urls from all categories and then scrapes all the urls.
